name: Full CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        cd api
        npm install
    - name: Run tests
      run: |
        cd api
        npm test

  cpp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get install -y g++ make
    - name: Build project
      run: |
        cd src
        g++ *.cpp data/*.cpp GameFlow/*.cpp -o main.exe
    - name: Run tests
      run: |
        cd src
        ./main