name: Full CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        cd api
        npm install
    - name: Run tests
      run: |
        cd api
        npm test

  cpp:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Download json.hpp
      run: |
        curl -L https://github.com/nlohmann/json/releases/latest/download/json.hpp -o src/data/json.hpp
    
    - name: Install dependencies
      run: |
        choco install mingw -y
        refreshenv

    - name: Build project
      run: |
        cd src
        g++ *.cpp data/*.cpp GameFlow/*.cpp -o main.exe
        
    - name: Run tests
      run: |
        cd src
        main.exe